### ISSUE TITLE
When manta LBs go away, manta-nfs blew up.

### ISSUE THREAD

**Issue by mcavage** [joyent/manta-nfs#1]
We had to fail out an LB in manta temporarily, and I happened to catch this since I had a long-lived keep-alive session going.

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Parse Error
    at CleartextStream.socketOnData (http.js:1583:20)
    at CleartextStream.read [as _read] (tls.js:511:12)
    at CleartextStream.Readable.read (_stream_readable.js:320:10)
    at EncryptedStream.write [as _write] (tls.js:366:25)
    at doWrite (_stream_writable.js:221:10)
    at writeOrBuffer (_stream_writable.js:211:5)
    at EncryptedStream.Writable.write (_stream_writable.js:180:11)
    at write (_stream_readable.js:583:24)
    at flow (_stream_readable.js:592:7)
    at Socket.pipeOnReadable (_stream_readable.js:624:5)
    at Socket.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:408:10)
```

**Comment by mvndaai** [comment]
Just and FYI. I was able to fix a similar error by adding an .on("error"..) to my http request.

<pre>
http.request(post, function(response) {
    ...
}).on("error", function(e){
	console.log("Got error: " + e.message);
});
</pre>
