### ISSUE TITLE
connect EACCES with ensure_manta_directory

### ISSUE THREAD

**Issue by hectcastro** [joyent/manta-nfs#19]
When I attempt to mount my Manta user directory, I get the following error:

```
vagrant@vagrant:~$ sudo mount -o nolock 127.0.0.1:/hectcastro ~/mnt -v
mount: no type was given - I'll assume nfs because of the colon
mount.nfs: timeout set for Tue Apr 29 16:48:14 2014
mount.nfs: trying text-based options 'nolock,vers=4,addr=127.0.0.1,clientaddr=127.0.0.1'
mount.nfs: mount(2): Protocol not supported
mount.nfs: trying text-based options 'nolock,addr=127.0.0.1'
mount.nfs: prog 100003, trying vers=3, prot=6
mount.nfs: trying 127.0.0.1 prog 100003 vers 3 prot TCP port 2049
mount.nfs: prog 100005, trying vers=3, prot=17
mount.nfs: portmap query retrying: RPC: Program not registered
mount.nfs: prog 100005, trying vers=3, prot=6
mount.nfs: trying 127.0.0.1 prog 100005 vers 3 prot TCP port 1892
mount.nfs: mount(2): Remote I/O error
mount.nfs: Remote I/O error
```

The error message emitted by `manta-nfs`:

``` javascript
{
    "name": "server.js",
    "hostname": "vagrant",
    "pid": 22032,
    "component": "RpcServer",
    "procedure": "mnt",
    "xid": 4057608624,
    "level": 40,
    "err": {
        "message": "connect EACCES",
        "name": "Error",
        "stack": "Error: connect EACCES\n    at errnoException (net.js:904:11)\n    at Object.afterConnect [as oncomplete] (net.js:895:19)",
        "code": "EACCES"
    },
    "msg": "ensure_manta_directory: info(/hectcastro) failed",
    "time": "2014-04-29T16:50:05.541Z",
    "src": {
        "file": "/home/vagrant/node_modules/manta-nfs/lib/mount.js",
        "line": 102
    },
    "v": 0
}
```

Executing a directory listing with `mls` appears to be fine:

```
vagrant@vagrant:~$ mls /hectcastro
jobs/
public/
reports/
stor/
```

**Comment by mariuspana** [comment]
Hi gang, Im hitting this same issue on centos7
